### PR TITLE
Remove Why and Who in GFX details.

### PR DESCRIPTION
**Pull request by Natim**
Remove why and who from the GFX details.

Question: Should we just hide them?

### CODE REVIEW

**Comment by n1k0** [comment]
> Question: Should we just hide them?

Are these fields presence required by clients in any way?

**Comment by Natim** [comment]
It is more because some records already have them filled with dots...

**Comment by n1k0** [comment]
> It is more because some records already have them filled with dots...

So if there's existing data we should keep them I guess. If these aren't expected to be modified, hiding might be just good enough.

**Comment by Natim** [comment]
It makes sense yes.

**Comment by Natim** [comment]
Updated.

**Pull request merged**
