### PR TITLE
Open the Versions section by default for add-ons and plugins, and display it above prefs

### LINKED ISSUE #41: the versions section should be active by default for add-ons and plugins
This is a request from @jvillalobos

### PR DESCRIPTION
**Pull request by magopian**
Fixes #41 #42

r? @n1k0 @natim

### CODE REVIEW

**Comment by n1k0** [comment]
For ordering the fields, react-jsonschema-form now has a [`ui:order` setting](https://github.com/mozilla-services/react-jsonschema-form#object-fields-ordering) which allows achieving the same thing and prevents relying on JSON key ordering which is never guaranteed to be the same.

**Comment by n1k0** [comment]
Note that defining an `uiSchema` in config file is supported by kinto-admin https://github.com/Kinto/kinto-admin/blob/master/config/config.json#L31

**Comment by magopian** [comment]
So react-jsonschema-form only supports having the ordering in the uiSchema since [version 0.9.0](https://github.com/mozilla-services/react-jsonschema-form/releases/tag/v0.9.0), but kinto-admin uses version 0.4.1.

I'm thus going to change this PR to only deal with #41, #42 will be dealt with in a future PR, when kinto-admin uses an udpated dependency.

**Comment by n1k0** [comment]
wfm, r+

**Comment by magopian** [comment]
@natim or @n1k0 can one of you merge this? I don't have the commit bit ;)

**Comment by n1k0** [comment]
Well, have a look at the notification above ;)

**Pull request merged**
