### PR TITLE
Add missing fields for Gfx (fixes #62)

### LINKED ISSUE #62: Add model,product,manufacturor,hardware to Gfx
See https://dxr.mozilla.org/mozilla-central/source/widget/GfxInfoBase.cpp#593-616

### PR DESCRIPTION
**Pull request by leplatrem**
Fixes #62

### CODE REVIEW

**Comment by magopian** [comment]
Only concern is the length of the form, but why not.

r+

**Comment by Natim** [comment]
These information ``model``, ``manufacturer`` and ``product``are not in the current implementation of the GFX blocklists in olympia ([Have a look at the model](https://github.com/mozilla/addons-server/blob/master/src/olympia/blocklist/models.py#L130-L154))

**Comment by Natim** [comment]
Does this works for you @leplatrem ?

**Comment by leplatrem** [comment]
I'm a bit embarassed because there is some code in android that uses it: https://hg.mozilla.org/mozilla-central/rev/f710f9f6f7ec

**Comment by leplatrem** [comment]
But those infos may come from the platform and not the blocklist. So yes, why not removing them.

**Pull request merged**
