### PR TITLE
Add GPU_PROCESS

### PR DESCRIPTION
**Pull request by Natim**
r? @jvillalobos

### CODE REVIEW

**Comment by Natim** [comment]
Refs https://dxr.mozilla.org/mozilla-central/source/gfx/config/gfxFeature.h#26

**Review by jvillalobos — APPROVED** [review]
r+

**Comment by Natim** [comment]
@leplatrem @glasserc can we validate that the blocklist code in Firefox will be able to load that new value?

**Comment by msreckovic** [comment]
GPU_PROCESS has been supported by Firefox since version 52, so let me know if I can help validate the above.

**Comment by msreckovic** [comment]
Indeed, it turns out we only had a partial support, which means it doesn't work properly.  I've opened https://bugzilla.mozilla.org/show_bug.cgi?id=1418980 for it.

**Pull request merged**
